# Template only. The original real sonar data are not redistributed.
path: /path/to/real_dataset
train: /path/to/real_train/images
val: /path/to/real_val/images
test: /path/to/real_test/images
names:
  0: body
  1: plane
  2: ship

