# Template for the FLUX+LoRA manual-600 synthetic subset.
# Download synthetic images from Kaggle. Real validation/test images are not redistributed.
path: /path/to/dataset
train: flux_lora_16_manual_600/images
val: /path/to/real_val/images
test: /path/to/real_test/images
names:
  0: body
  1: plane
  2: ship

